app:
  project_name: "Exact 2026"
  version: "1.0.0"
  debug: true

llm:
  model_path: "DeepSeek-R1-0528-Qwen3-8B.gguf"
  temperature: 0.0

rag:
  reranker: "bge-reranker-base"

embedding:
  model_name: "BAAI/bge-m3"
  base_url: "http://localhost:11434"

retrieval:
  threshold: 0.5
  top_k: 5

storage:
  data_dir: "data"
  vector_db: "storage/vector_db"
  collection_name: "exact"

langsmith:
  project: "Exact 2026"
  endpoint: "https://api.smith.langchain.com"