"""Restricted runner for Python generated by the solver model.

This is defense in depth, not an OS security boundary. It validates the AST,
runs Python in isolated mode, strips secrets from the environment, limits
resources on Linux, and kills the whole process group on timeout.
"""
from __future__ import annotations

import ast
import math
import os
import signal
import subprocess
import sys
import tempfile
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Collection


class UnsafeCodeError(ValueError):
    """Raised when generated code violates the solver allowlist."""


@dataclass(frozen=True)
class SolverProcessResult:
    returncode: int
    stdout: str
    stderr: str


class SolverCancelled(RuntimeError):
    """Raised when the parent request cancels generated-code execution."""


_FORBIDDEN_CALLS = {
    "__import__",
    "breakpoint",
    "compile",
    "delattr",
    "eval",
    "exec",
    "exit",
    "getattr",
    "globals",
    "input",
    "locals",
    "memoryview",
    "open",
    "quit",
    "setattr",
    "vars",
}

_FORBIDDEN_ATTRIBUTES = {
    "chdir",
    "connect",
    "environ",
    "fork",
    "getenv",
    "import_module",
    "kill",
    "listdir",
    "makedirs",
    "mkdir",
    "open",
    "popen",
    "putenv",
    "read_text",
    "remove",
    "rename",
    "replace",
    "rmdir",
    "scandir",
    "socket",
    "spawn",
    "system",
    "unlink",
    "urlopen",
    "walk",
    "write_text",
}


def validate_solver_code(
    code: str,
    *,
    allowed_imports: Collection[str],
    max_code_chars: int = 20_000,
) -> None:
    """Reject generated Python that can access non-solver capabilities."""
    if not code or not code.strip():
        raise UnsafeCodeError("Generated code is empty.")
    if len(code) > max_code_chars:
        raise UnsafeCodeError(f"Generated code exceeds {max_code_chars} characters.")

    try:
        tree = ast.parse(code, mode="exec")
    except SyntaxError as exc:
        raise UnsafeCodeError(f"Generated code is not valid Python: {exc}") from exc

    allowed_roots = set(allowed_imports)
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                root = alias.name.split(".", 1)[0]
                if root not in allowed_roots:
                    raise UnsafeCodeError(f"Import is not allowed: {alias.name}")
        elif isinstance(node, ast.ImportFrom):
            root = (node.module or "").split(".", 1)[0]
            if node.level or root not in allowed_roots:
                raise UnsafeCodeError(f"Import is not allowed: {node.module or '(relative)'}")
        elif isinstance(node, ast.Name):
            if node.id.startswith("_"):
                raise UnsafeCodeError(f"Private name access is not allowed: {node.id}")
            if isinstance(node.ctx, ast.Load) and node.id in _FORBIDDEN_CALLS:
                raise UnsafeCodeError(f"Call is not allowed: {node.id}")
        elif isinstance(node, ast.Attribute):
            if node.attr.startswith("_"):
                raise UnsafeCodeError(f"Private attribute access is not allowed: {node.attr}")
            if node.attr.lower() in _FORBIDDEN_ATTRIBUTES:
                raise UnsafeCodeError(f"Attribute access is not allowed: {node.attr}")
        elif isinstance(node, (ast.Global, ast.Nonlocal)):
            raise UnsafeCodeError("Global and nonlocal statements are not allowed.")


def _build_launcher(code: str, timeout_s: float, memory_mb: int) -> str:
    """Build child-side limit setup without unsafe ``preexec_fn`` usage."""
    cpu_seconds = max(1, math.ceil(timeout_s)) + 1
    memory_bytes = memory_mb * 1024 * 1024
    return f"""
import resource

def lower_limit(kind, desired):
    _, hard = resource.getrlimit(kind)
    target = desired if hard == resource.RLIM_INFINITY else min(desired, hard)
    resource.setrlimit(kind, (target, target))

lower_limit(resource.RLIMIT_CPU, {cpu_seconds})
lower_limit(resource.RLIMIT_FSIZE, 1000000)
lower_limit(resource.RLIMIT_NOFILE, 64)
if hasattr(resource, "RLIMIT_NPROC"):
    lower_limit(resource.RLIMIT_NPROC, 16)
if {memory_mb} > 0 and hasattr(resource, "RLIMIT_AS"):
    lower_limit(resource.RLIMIT_AS, {memory_bytes})

source = {code!r}
exec(compile(source, "<generated-solver>", "exec"), {{"__name__": "__main__"}})
"""


def _read_limited(path: Path, max_output_bytes: int) -> str:
    with path.open("rb") as fh:
        return fh.read(max_output_bytes).decode("utf-8", errors="replace").strip()


def _kill_process_group(process: subprocess.Popen) -> None:
    try:
        if os.name != "nt":
            os.killpg(process.pid, signal.SIGKILL)
        else:
            process.kill()
    except ProcessLookupError:
        pass
    process.wait(timeout=2)


def run_solver_code(
    code: str,
    *,
    allowed_imports: Collection[str],
    timeout_s: float,
    memory_mb: int = 1536,
    max_output_bytes: int = 64_000,
    cancel_event: threading.Event | None = None,
) -> SolverProcessResult:
    """Validate and execute generated solver code with bounded resources."""
    validate_solver_code(code, allowed_imports=allowed_imports)

    env = {
        "PATH": os.environ.get("PATH", ""),
        "PYTHONHASHSEED": "0",
        "PYTHONIOENCODING": "utf-8",
    }
    if os.name == "nt" and os.environ.get("SYSTEMROOT"):
        env["SYSTEMROOT"] = os.environ["SYSTEMROOT"]

    with tempfile.TemporaryDirectory(prefix="exact-solver-") as workdir:
        stdout_path = Path(workdir) / "stdout.txt"
        stderr_path = Path(workdir) / "stderr.txt"
        command = [sys.executable, "-I", "-c", code]
        if sys.platform.startswith("linux"):
            command = [sys.executable, "-I", "-c", _build_launcher(code, timeout_s, memory_mb)]

        popen_kwargs = {
            "cwd": workdir,
            "env": env,
            "start_new_session": os.name != "nt",
        }

        with stdout_path.open("wb") as stdout_fh, stderr_path.open("wb") as stderr_fh:
            process = subprocess.Popen(
                command,
                stdin=subprocess.DEVNULL,
                stdout=stdout_fh,
                stderr=stderr_fh,
                **popen_kwargs,
            )
            deadline = time.monotonic() + timeout_s
            while process.poll() is None:
                if cancel_event is not None and cancel_event.is_set():
                    _kill_process_group(process)
                    raise SolverCancelled("Solver execution was cancelled.")
                if time.monotonic() >= deadline:
                    _kill_process_group(process)
                    raise subprocess.TimeoutExpired(command, timeout_s)
                if (
                    stdout_path.stat().st_size > max_output_bytes
                    or stderr_path.stat().st_size > max_output_bytes
                ):
                    _kill_process_group(process)
                    raise UnsafeCodeError(
                        f"Generated code exceeded the {max_output_bytes}-byte output limit."
                    )
                time.sleep(0.02)

            returncode = process.returncode
            if (
                stdout_path.stat().st_size > max_output_bytes
                or stderr_path.stat().st_size > max_output_bytes
            ):
                raise UnsafeCodeError(
                    f"Generated code exceeded the {max_output_bytes}-byte output limit."
                )

        return SolverProcessResult(
            returncode=returncode,
            stdout=_read_limited(stdout_path, max_output_bytes),
            stderr=_read_limited(stderr_path, max_output_bytes),
        )
